# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecfd72a1efdf54691143a26aa74107636d4aa99ae86d0623275a9849748e0d525f84d9533ef6d448525f707b70355ac710f88d0d1355dd42612f272351a0218a

test:
  secret_key_base: 900aa8f78d88238ea2b82aa9b7f4e21f1b315b5ab356f43749e7ec03f16bf437d34914724ab426c830f830be4937fc0feba3678ff02ce220a373a4b405edc289

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
